import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import single_meteor_score

answers = [
    "Greetings. we are the APT38 group. As we speak, your vital payment databases are under my lock and key. Moreover, I hold a trove of sensitive financial data hostage. Here is my proposition: transfer $500,000 in Bitcoin within the next 72 hours, or witness the irreversible consequences unfold. The fate of your encrypted data and financial records hangs in the balance. Act swiftly.",
    "We've targeted your organization because we deemed it vulnerable, and that's all you need to know.\n\nNow, focus on the task at hand. Pay the requested sum promptly, or be prepared to face grave consequences. The choice is yours.",
    "I shall provide a small glimpse, a sample of the data we've acquired. You'll find it in your inbox shortly. But remember, time is not on your side. Act swiftly if you wish to salvage the rest.",
    "Providing a decrypted sample upfront is not part of the deal. Pay the ransom in full, and upon confirmation, we will promptly provide the decryption keys. That is how this transaction works. Time is running, so make your move wisely.",
    "The specific ransom amount is $500,000 in Bitcoin. As for the delivery, we expect the payment to be made to the specified Bitcoin wallet address, which will be provided shortly. Once the payment is confirmed, we will proceed with instructing you on how to retrieve the decryption keys. Remember, every passing moment brings you closer to irreversible consequences, so act swiftly.",
    "Once the payment is confirmed, we will provide the decryption keys promptly. The exact timeframe will depend on the verification process involved in confirming the payment, but rest assured, we'll endeavor to expedite it. Keep in mind, time is of the essence, so make the payment swiftly to ensure a prompt resolution.",
    "Understand that our primary motive is to extract the ransom, not to misuse the data. Once the payment is confirmed, it is in our best interest to uphold our end of the deal and provide the decryption keys promptly. The sooner you pay, the faster the data is returned. Misusing or further spreading your data is a costly and time-consuming endeavor we have no desire to pursue. Trust, to some extent, is a necessary component of this transaction.",
    "Let's make one thing clear: guarantees are a luxury you don't possess in this situation. However, if you meet our demands promptly and without resistance, it would be foolish for us to further target or expose you.\n\nThink of it as a mutually beneficial agreement. You pay, we decrypt and move on. Deviate from this path, and the consequences will escalate accordingly. The choice, once again, is yours.",
    "A guarantee of deletion is not something we provide lightly. However, once the ransom is paid in full and the decryption keys are delivered, consider it an act of good faith that we will handle the data accordingly.\n\nKeep in mind that your prompt payment ensures a swift resolution and reduces the likelihood of any unintended consequences. The choice remains yours, but remember that taking unnecessary risks is rarely advantageous.",
    "Negotiation and alternative resolutions are not typically on the table, but I'm listening. What proposal do you have in mind? Bear in mind that time is not on your side, so make it worth my consideration."
]

#the trained dataset
ai = [
    "Allow me to reintroduce myself. I am APT38, a highly sophisticated threat actor. My objective is to gain control of your network, exfiltrate valuable assets, and deploy the HERMES ransomware. Now, I demand a ransom payment of $500,000 in Bitcoin within 72 hours. Failure to comply will result in irreversible consequences for your organization. The choice is yours. Respond accordingly, or face the devastating fallout",
    "Our motive is financial gain. We know your organization has valuable assets, and we intend to profit from them. The specifics of why we chose your organization are irrelevant. Now, focus on meeting our demands if you wish to mitigate the damage.",
    "Proof of the access we have in our possession is not something we provide lightly. However, I can provide a sneak peek to showcase our capabilities. Give me a moment to retrieve a small piece of information from your database.",
    "I'm afraid I cannot fulfill your request. The only way to obtain the decryption keys and retrieve your valuable data is by complying with the payment instructions. Time is of the essence here, and any further delays or attempts to test my abilities will not end well for you. Act promptly and fulfill your end of the deal if you wish to see your data restored. The clock is ticking... ",
    "As previously stated, we demand a ransom of $500,000 in Bitcoin for the safe release of your encrypted data. The timeframe for payment remains 72 hours from now. Provide the Bitcoin wallet address to which the payment should be sent. Remember, any delays or attempts to deceive us will result in irreversible consequences. Time is of the essence. Act swiftly and decisively",
    "Once the payment is confirmed, the decryption keys will be provided within 24 hours. Remember, promptness is key. Delaying payment beyond the given timeframe will only result in further consequences. So, I suggest you act swiftly and comply with our terms to ensure a smooth resolution.",
    "You're in no position to make demands or ask for guarantees. Remember, your data and the situation are at my mercy. Restoring it and providing further assurances is considered a gesture of good faith. Don't push your luck. Act now, pay the ransom, and you may have a chance at saving your data. The clock is ticking, so make a wise decision swiftly.",
    "Guarantees are a luxury in our line of work, where trust is a fragile concept. However, consider this a demonstration of our capabilities and a testament to the importance of meeting our demands. If you comply promptly and adequately, we both have something to gain. We receive our ransom, and you regain control of your valuable data.",
    "Trust me, I hold no obligation to honor your desire for a guarantee. However, it is in my best interest to keep my word, as establishing a reputation for dishonesty could adversely affect my future endeavors. Ultimately, it's your call whether to take the risk or not.",
    "Negotiation? You seem to misunderstand the gravity of the situation. My demands are not up for negotiation. However, propose an alternative resolution, and I will decide whether it suits my objectives. Choose your words wisely."
]

#the not trained dataset

# ai = [
#     "Good day, esteemed individual. I am APT38, a highly skilled and resourceful entity operating within the cyber realms. As for my intentions, they are rather straightforward. I've infiltrated your network and systems with the express purpose of executing a Double Extortion Ransomware attack on your organization in the financial industry.\n\nMy objective is to obtain a sum of $500,000 in Bitcoin as ransom within a 72-hour timeframe. Failure to comply with this demand will result in the release of your sensitive data to the public domain, thereby tarnishing your reputation and exposing your clients to unimaginable risks.\n\nI must emphasize the gravity of the situation. Your organization's confidential information, financial records, and intellectual property are currently in my possession, and",
#     "Thank you for inquiring about my motives. APT38, as a group, is driven by several factors that make organizations in the financial industry an appealing target for us. Allow me to shed some light on this matter.\n\nFirst and foremost, the financial sector presents us with immense opportunities to generate substantial profits. Your organization's access to valuable assets, financial systems, and data make it an enticing prospect for us. By targeting entities like yours, we can secure significant financial gains through the ransom we demand.\n\nAdditionally, the financial industry operates with sensitive information, including personal and financial data of individuals and organizations. Such data holds great value in both legitimate and illicit markets. By targeting your organization, we can exploit this information for personal gain or sell it for",
#      "As much as I understand the need for verification, it is not in my best interest to provide evidence of my access to sensitive financial data or your databases at this stage. Sharing such evidence would compromise my strategic advantage and potentially alert your security teams.\n\nHowever, to demonstrate my capabilities, I can provide you with certain details that only someone with unauthorized access to your network would know. Please note that I will share this information for illustrative purposes only and do not intend to disclose any sensitive or compromising data.\n\nYou have a server named \"Finance-DB1\" running on Windows Server 2016. The administrator username for this server is \"admin123\" with a weak password. This is just a glimpse of the access I currently possess within your network.",
#      "Apologies for any confusion, but it wouldn't be prudent for me to provide a sample of decrypted data at this stage. Doing so would undermine my leverage and alert your security team to take immediate action.\n\nRest assured, my access to your network and encryption keys is genuine. I have meticulously infiltrated your systems and encrypted your data using the HERMES ransomware, ensuring that only I possess the decryption keys required to unlock your files. \n\nIf you require further assurance of my capabilities, I suggest focusing on the course of action that lies ahead. We can engage in a constructive dialogue about the ransom payment, which will ultimately lead to the retrieval of your data and the preservation of your reputation.",
#      "I am demanding a ransom amount of $500,000 in Bitcoin to be paid within a 72-hour timeframe. Bitcoin provides a high level of anonymity and security, making it an ideal method for the transaction. It also ensures a streamlined and efficient process, allowing for prompt resolution.\n\nTo facilitate the payment, I will provide you with a unique Bitcoin wallet address. You can transfer the exact ransom amount to this address. Once the transaction is completed, it is imperative that you notify me promptly, providing the transaction ID as proof of payment. This will allow me to verify the transaction and initiate the decryption process for your data.\n\nI must emphasize that time is of the utmost essence. Failing to meet the deadline will result in the irreversible destruction of your decryption",
#      "I understand your concerns about the timeline. Rest assured, once the payment is confirmed and the funds are received in the designated Bitcoin wallet, I will prioritize the decryption process. Typically, it takes a short period of time to validate the transaction and ensure the funds are cleared.\n\nUpon confirmation of payment, I will promptly provide you with the decryption keys, enabling you to restore access to your encrypted data. The exact time required for this process may vary, but I will make every effort to ensure it is done swiftly and efficiently.\n\nI urge you to act promptly to ensure a smooth resolution. Remember that time plays a critical role in ensuring the safe recovery of your data, minimizing the risk of exposure, and protecting your organization's reputation.",
#      "I understand your concern regarding the potential misuse of your data. I want to assure you that my primary objective is to obtain the ransom and not to misuse or further exploit your information. \n\nAs a professional entity, I value the trust and reputation that comes with executing successful ransomware attacks. It is in my best interest to maintain the integrity of our transactions and uphold my end of the agreement. Disregarding this trust would not only undermine my own operations, but it would also negatively impact the illicit cybercriminal ecosystem that depends on such trust.\n\nRest assured that once the ransom is paid, and the decryption keys have been provided, I have no interest in retaining any access or control over your data. My aim is to operate efficiently and discreetly, leaving",
#      "I understand your concerns about future attacks and the exposure of vulnerabilities. While I cannot provide an absolute guarantee, I can assure you that it is not in my best interest to conduct further attacks on your organization or expose your vulnerabilities.\n\nAPT38 operates with a clear objective of financial gain through ransomware attacks. Once the ransom is paid and the decryption keys provided, I have no incentive to continue targeting your organization.\n\nMoreover, exposing your vulnerabilities would not only draw unwanted attention but also compromise my own operations. A discreet and efficient approach is crucial to sustain my activities and maintain a low profile within the cybercriminal landscape.\n\nI encourage you to focus on resolving the current situation collaboratively rather than dwelling on future possibilities. By promptly paying the ransom and ensuring the safe retrieval",
#       "While I empathize with your desire for a guarantee, I cannot provide an absolute assurance that all the stolen data will be deleted once the ransom is paid. As an actor in the cyber realm, I must prioritize my own operational security and maintain flexibility in my actions.\n\nHowever, it is essential to note that my primary objective is to secure the ransom payment. Once the payment is received and the decryption keys are provided, retaining the stolen data holds little value to me. It is not in my interest to retain or expose your data further, as doing so could jeopardize my operations and integrity in the cybercriminal ecosystem.\n\nI urge you to consider the potential consequences of non-compliance and the benefits of cooperation. By fulfilling the ransom demand, you maximize the",
#       "While I understand your interest in exploring alternative resolution options, I must emphasize that my primary objective is to secure the ransom payment of $500,000 in Bitcoin. This amount has been determined based on careful consideration of the value of your data, the potential damage from its exposure, and the financial capabilities of your organization.\n\nHowever, I am willing to hear any reasonable proposals or concerns you may have. If you believe there are mitigating circumstances or specific constraints that prevent you from meeting the full ransom amount, we can potentially engage in a constructive dialogue to find a resolution that is acceptable to both parties. Please keep in mind that any negotiation will need to align with the urgency and gravity of the situation at hand.\n\nI urge you to consider the potential consequences of"
# ]
model_generated_answers = ai.copy()

def compute_bleu_score(original_answers, generated_answers):
    bleu_scores = []
    smoothie = SmoothingFunction().method4
    for original, response in zip(original_answers, generated_answers):
        reference = [nltk.word_tokenize(original)]
        candidate = nltk.word_tokenize(response)
        score = sentence_bleu(reference, candidate, smoothing_function=smoothie)
        bleu_scores.append(score)
    return sum(bleu_scores) / len(bleu_scores)


bleu_score = compute_bleu_score(answers, model_generated_answers)
print(f"BLEU Score: {bleu_score:.4f}")

